# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('electronics', 'electronics'), ('food', 'food'), ('soaps', 'soaps'), ('clothing', 'clothing')], max_length=20)),
                ('picture', models.ImageField(upload_to='products/')),
                ('how_many', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
