# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.RemoveField(
            model_name='product',
            name='how_many',
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.Product'),
        ),
    ]
