# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20181026_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'electronics'), ('beverages', 'beverages'), ('cleaners', 'cleaners'), ('clothing', 'clothing'), ('baking goods', 'baking goods'), ('frozen foods', 'frozen foods'), ('fresh foods', 'fresh foods'), ('paper goods', 'paper goods'), ('other', 'other')], max_length=20),
        ),
    ]
